STORAGE:
  type: "mysql"
  IP: "localhost"
  PORT: 3306
  USERNAME: "root"
  DATABASE: "db"
  PASSWORD: "password"

MODULES:
  world-manager: true

HOOKS:
  Bulmultiverse: true

DOMAIN:
  world-type: FLAT
  sounds:
    - sound: BLOCK_BEACON_ACTIVATE
      volume: 1.0
      pitch: 0.6
      delay: 0
    - sound: BLOCK_END_PORTAL_FRAME_FILL
      volume: 1.0
      pitch: 0.8
      delay: 10
    - sound: ENTITY_ENDER_DRAGON_GROWL
      volume: 0.8
      pitch: 0.5
      delay: 20
    - sound: BLOCK_END_PORTAL_SPAWN
      volume: 1.0
      pitch: 0.7
      delay: 30
    - sound: ENTITY_GENERIC_EXPLODE
      volume: 0.9
      pitch: 0.4
      delay: 40
    - sound: ITEM_TOTEM_USE
      volume: 1.0
      pitch: 1.2
      delay: 50