name: JujutsuWorld
version: '${version}'

main: dev.lorenzz.jujutsuWorld.JujutsuWorld
api-version: '1.21'

softdepend: [BulMultiverse]

permissions:
  jujutsu.domainexpansion.use:
    description: Permette di creare un dominio personale con /domainexpansion.
    default: true
  jujutsu.admin.reload:
    description: Permette di ricaricare la configurazione con /expansionadmin reload.
    default: op